# Script

name: test

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CRD Link'
        required: true
      pincode:
        description: '6 Digit pincode'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./main.ps1
    - name: CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Install depends
      run: Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -File .\load.ps1" -Verb RunAs
    - name: Timeout
      run: ./timeout.ps1
      env:
        ARGS: "-av"
